[CmdletBinding()]
param(
    [string]$ProjectRoot = "",
    [ValidateSet("phase5-ready", "phase6-reject", "task-group", "ready-ui", "approval")]
    [string]$Scenario = "phase5-ready",
    [string]$RunId = "",
    [int]$TaskCount = 3,
    [switch]$Force
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Resolve-RelayDevProjectRoot {
    param([string]$StartPath)

    $candidate = if ([string]::IsNullOrWhiteSpace($StartPath)) { (Get-Location).Path } else { $StartPath }
    $candidate = [System.IO.Path]::GetFullPath($candidate)
    if (Test-Path -LiteralPath $candidate -PathType Leaf) {
        $candidate = Split-Path -Parent $candidate
    }

    while (-not [string]::IsNullOrWhiteSpace($candidate)) {
        if ((Test-Path -LiteralPath (Join-Path $candidate "app\core\run-state-store.ps1")) -and
            (Test-Path -LiteralPath (Join-Path $candidate "app\core\artifact-repository.ps1"))) {
            return $candidate
        }

        $parent = Split-Path -Parent $candidate
        if ($parent -eq $candidate) {
            break
        }
        $candidate = $parent
    }

    throw "Could not find a relay-dev project root from '$StartPath'. Pass -ProjectRoot explicitly."
}

function New-DummyTask {
    param(
        [Parameter(Mandatory)][string]$TaskId,
        [string]$ParallelSafety = "parallel",
        [string[]]$DependsOn = @()
    )

    $dependencyList = @(
        @($DependsOn) |
            ForEach-Object { [string]$_ } |
            Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
    )

    return [ordered]@{
        task_id = $TaskId
        purpose = "Dummy task $TaskId for relay-dev verification"
        changed_files = @("src/$TaskId.txt")
        acceptance_criteria = @("Dummy scenario can be inspected safely")
        boundary_contract = [ordered]@{
            module_boundaries = @("dummy/$TaskId")
            public_interfaces = @("$TaskId public contract")
            allowed_dependencies = @("$TaskId -> local dummy dependency")
            forbidden_dependencies = @("$TaskId -> production side effect")
            side_effect_boundaries = @("$TaskId owns only dummy files")
            state_ownership = @("$TaskId owns dummy state")
        }
        visual_contract = [ordered]@{
            mode = "not_applicable"
            design_sources = @()
            visual_constraints = @()
            component_patterns = @()
            responsive_expectations = @()
            interaction_guidelines = @()
        }
        dependencies = @($dependencyList)
        depends_on = @($dependencyList)
        tests = @("pwsh -NoLogo -NoProfile -Command `"Write-Host dummy test for $TaskId`"")
        complexity = "small"
        resource_locks = @("file:src/$TaskId.txt")
        parallel_safety = $ParallelSafety
    }
}

function New-DummyTasks {
    param([int]$Count = 3)

    $tasks = New-Object System.Collections.Generic.List[object]
    for ($index = 1; $index -le [Math]::Max(1, $Count); $index++) {
        $taskId = "T-{0:D2}" -f $index
        $safety = "parallel"
        if ($index -eq 2) { $safety = "cautious" }
        if ($index -eq 3) { $safety = "serial" }
        $dependsOn = if ($index -eq 3) { @("T-01") } else { [string[]]@() }
        $tasks.Add((New-DummyTask -TaskId $taskId -ParallelSafety $safety -DependsOn $dependsOn)) | Out-Null
    }

    return @($tasks.ToArray())
}

function New-Phase0Context {
    param(
        [Parameter(Mandatory)][string]$Root,
        [Parameter(Mandatory)][string]$RunId
    )

    return [ordered]@{
        project_summary = "Dummy relay-dev run $RunId for local verification"
        project_root = $Root
        framework_root = $Root
        constraints = @("Generated by relay-dev-dummy-run skill", "Do not treat as production evidence")
        available_tools = @("pwsh", "relay-dev core scripts")
        risks = @("Dummy data may not represent every artifact nuance")
        open_questions = @("No open questions for this dummy run")
        design_inputs = @()
        visual_constraints = @()
        task_fingerprint = "dummy-$RunId"
        task_path = (Join-Path $Root "tasks\task.md")
        seed_created_at = (Get-Date).ToString("o")
    }
}

function Save-DummyArtifact {
    param(
        [Parameter(Mandatory)]$ArtifactPaths,
        [Parameter(Mandatory)][string]$ProjectRoot,
        [Parameter(Mandatory)][string]$RunId,
        [Parameter(Mandatory)][ValidateSet("run", "task")][string]$Scope,
        [Parameter(Mandatory)][string]$Phase,
        [Parameter(Mandatory)][string]$ArtifactId,
        [Parameter(Mandatory)]$Content,
        [string]$TaskId
    )

    $path = Save-Artifact -ProjectRoot $ProjectRoot -RunId $RunId -Scope $Scope -Phase $Phase -ArtifactId $ArtifactId -Content $Content -TaskId $TaskId -AsJson
    $ArtifactPaths.Add([ordered]@{
        scope = $Scope
        phase = $Phase
        artifact_id = $ArtifactId
        task_id = if ([string]::IsNullOrWhiteSpace($TaskId)) { $null } else { $TaskId }
        path = $path
    }) | Out-Null
}

function New-Phase5Result {
    param([Parameter(Mandatory)][string]$TaskId)

    return [ordered]@{
        task_id = $TaskId
        changed_files = @("src/$TaskId.txt")
        commands_run = @("dummy implementation command")
        implementation_summary = "Dummy implementation for $TaskId"
        acceptance_criteria_status = @(
            [ordered]@{ criterion = "Dummy scenario can be inspected safely"; status = "pass"; notes = "Generated artifact" }
        )
        known_issues = @()
    }
}

function New-Phase51Verdict {
    param([Parameter(Mandatory)][string]$TaskId)

    return [ordered]@{
        task_id = $TaskId
        verdict = "go"
        rollback_phase = ""
        must_fix = @()
        warnings = @()
        evidence = @("phase5_result.json")
        acceptance_criteria_checks = @(
            [ordered]@{ criterion = "Dummy scenario can be inspected safely"; status = "pass"; notes = "Generated check"; evidence = @("phase5_result.json") }
        )
        review_checks = @(
            [ordered]@{ check_id = "selected_task_alignment"; status = "pass"; notes = "Dummy task matches itself"; evidence = @("phase4_tasks.json") }
            [ordered]@{ check_id = "acceptance_criteria_coverage"; status = "pass"; notes = "Dummy acceptance covered"; evidence = @("phase5_result.json") }
            [ordered]@{ check_id = "changed_files_audit"; status = "pass"; notes = "Changed files are scoped"; evidence = @("phase5_result.json") }
            [ordered]@{ check_id = "test_evidence_review"; status = "pass"; notes = "Dummy test evidence present"; evidence = @("phase5_result.json") }
            [ordered]@{ check_id = "design_boundary_alignment"; status = "pass"; notes = "Boundary is dummy-only"; evidence = @("phase4_tasks.json") }
            [ordered]@{ check_id = "visual_contract_alignment"; status = "not_applicable"; notes = "No visual contract"; evidence = @() }
        )
    }
}

function New-Phase52Verdict {
    param([Parameter(Mandatory)][string]$TaskId)

    return [ordered]@{
        task_id = $TaskId
        verdict = "go"
        rollback_phase = ""
        must_fix = @()
        warnings = @()
        evidence = @("phase5-1_verdict.json")
        security_checks = @(
            [ordered]@{ check_id = "input_validation"; status = "pass"; notes = "Dummy input only"; evidence = @("phase5_result.json") }
            [ordered]@{ check_id = "authentication_authorization"; status = "not_applicable"; notes = "No auth surface"; evidence = @() }
            [ordered]@{ check_id = "secret_handling_and_logging"; status = "pass"; notes = "No secrets"; evidence = @("phase5_result.json") }
            [ordered]@{ check_id = "dangerous_side_effects"; status = "pass"; notes = "No real side effects"; evidence = @("phase4_tasks.json") }
            [ordered]@{ check_id = "dependency_surface"; status = "pass"; notes = "No new dependencies"; evidence = @("phase5_result.json") }
        )
        open_requirements = @()
        resolved_requirement_ids = @()
    }
}

function New-Phase6Result {
    param(
        [Parameter(Mandatory)][string]$TaskId,
        [ValidateSet("go", "conditional_go", "reject")][string]$Verdict = "go",
        [string]$RollbackPhase = ""
    )

    $failed = if ($Verdict -eq "reject") { 1 } else { 0 }
    return [ordered]@{
        task_id = $TaskId
        test_command = "pwsh -NoLogo -NoProfile -Command `"Write-Host dummy test`""
        lint_command = "pwsh -NoLogo -NoProfile -Command `"Write-Host dummy lint`""
        tests_passed = 3
        tests_failed = $failed
        coverage_line = 80
        coverage_branch = 75
        verdict = $Verdict
        rollback_phase = $RollbackPhase
        conditional_go_reasons = @()
        verification_checks = @(
            [ordered]@{ check_id = "lint_static_analysis"; status = "pass"; notes = "Dummy lint passed"; evidence = @("dummy lint") }
            [ordered]@{ check_id = "automated_tests"; status = $(if ($Verdict -eq "reject") { "fail" } else { "pass" }); notes = "Generated for $Verdict scenario"; evidence = @("dummy test") }
            [ordered]@{ check_id = "regression_scope"; status = "pass"; notes = "Dummy scope only"; evidence = @("phase4_tasks.json") }
            [ordered]@{ check_id = "error_path_coverage"; status = "not_applicable"; notes = "No error path in dummy"; evidence = @() }
            [ordered]@{ check_id = "coverage_assessment"; status = "pass"; notes = "Dummy coverage numbers"; evidence = @("coverage_line") }
        )
        open_requirements = @()
        resolved_requirement_ids = @()
    }
}

function Add-CompletedTaskArtifacts {
    param(
        [Parameter(Mandatory)]$ArtifactPaths,
        [Parameter(Mandatory)][string]$ProjectRoot,
        [Parameter(Mandatory)][string]$RunId,
        [Parameter(Mandatory)][string]$TaskId,
        [ValidateSet("go", "reject")][string]$Phase6Verdict = "go",
        [string]$RollbackPhase = ""
    )

    Save-DummyArtifact -ArtifactPaths $ArtifactPaths -ProjectRoot $ProjectRoot -RunId $RunId -Scope task -TaskId $TaskId -Phase "Phase5" -ArtifactId "phase5_result.json" -Content (New-Phase5Result -TaskId $TaskId)
    Save-DummyArtifact -ArtifactPaths $ArtifactPaths -ProjectRoot $ProjectRoot -RunId $RunId -Scope task -TaskId $TaskId -Phase "Phase5-1" -ArtifactId "phase5-1_verdict.json" -Content (New-Phase51Verdict -TaskId $TaskId)
    Save-DummyArtifact -ArtifactPaths $ArtifactPaths -ProjectRoot $ProjectRoot -RunId $RunId -Scope task -TaskId $TaskId -Phase "Phase5-2" -ArtifactId "phase5-2_verdict.json" -Content (New-Phase52Verdict -TaskId $TaskId)
    Save-DummyArtifact -ArtifactPaths $ArtifactPaths -ProjectRoot $ProjectRoot -RunId $RunId -Scope task -TaskId $TaskId -Phase "Phase6" -ArtifactId "phase6_result.json" -Content (New-Phase6Result -TaskId $TaskId -Verdict $Phase6Verdict -RollbackPhase $RollbackPhase)
}

function Set-DummyTaskState {
    param(
        [Parameter(Mandatory)]$RunState,
        [Parameter(Mandatory)][string]$TaskId,
        [string]$Status,
        [string]$PhaseCursor,
        [string]$LastCompletedPhase = "",
        [string]$WaitReason = "",
        [string]$ActiveJobId = ""
    )

    $task = ConvertTo-RelayHashtable -InputObject $RunState["task_states"][$TaskId]
    if (-not $task) {
        throw "Task '$TaskId' is not registered."
    }

    if (-not [string]::IsNullOrWhiteSpace($Status)) { $task["status"] = $Status }
    if (-not [string]::IsNullOrWhiteSpace($PhaseCursor)) { $task["phase_cursor"] = $PhaseCursor }
    if (-not [string]::IsNullOrWhiteSpace($LastCompletedPhase)) { $task["last_completed_phase"] = $LastCompletedPhase }
    if (-not [string]::IsNullOrWhiteSpace($WaitReason)) { $task["wait_reason"] = $WaitReason }
    if (-not [string]::IsNullOrWhiteSpace($ActiveJobId)) { $task["active_job_id"] = $ActiveJobId }
    $RunState["task_states"][$TaskId] = $task
}

$ProjectRoot = Resolve-RelayDevProjectRoot -StartPath $ProjectRoot
$coreRoot = Join-Path $ProjectRoot "app\core"
. (Join-Path $coreRoot "run-state-store.ps1")
. (Join-Path $coreRoot "artifact-repository.ps1")
. (Join-Path $coreRoot "workflow-engine.ps1")

if ([string]::IsNullOrWhiteSpace($RunId)) {
    $RunId = "dummy-$Scenario-$((Get-Date).ToString("yyyyMMdd-HHmmss"))"
}

$runRoot = Get-RunRootPath -ProjectRoot $ProjectRoot -RunId $RunId
if ((Test-Path -LiteralPath $runRoot) -and -not $Force) {
    throw "Run '$RunId' already exists at '$runRoot'. Pass -Force or choose another -RunId."
}
if ((Test-Path -LiteralPath $runRoot) -and $Force) {
    Remove-Item -LiteralPath $runRoot -Recurse -Force
}
New-Item -ItemType Directory -Path $runRoot -Force | Out-Null

$artifactPaths = New-Object System.Collections.Generic.List[object]
$tasks = @(New-DummyTasks -Count $TaskCount)
$tasksArtifact = [ordered]@{ tasks = @($tasks) }
$phase = switch ($Scenario) {
    "phase5-ready" { "Phase5" }
    "phase6-reject" { "Phase6" }
    "task-group" { "Phase5" }
    "ready-ui" { "Phase5" }
    "approval" { "Phase5-1" }
}

$state = New-RunState -RunId $RunId -ProjectRoot $ProjectRoot -TaskId "dummy-main" -CurrentPhase $phase -CurrentRole "implementer"
$state = Register-PlannedTasks -RunState $state -TasksArtifact $tasksArtifact
$state["task_lane"]["mode"] = "parallel"
$state["task_lane"]["max_parallel_jobs"] = 3

Save-DummyArtifact -ArtifactPaths $artifactPaths -ProjectRoot $ProjectRoot -RunId $RunId -Scope run -Phase "Phase0" -ArtifactId "phase0_context.json" -Content (New-Phase0Context -Root $ProjectRoot -RunId $RunId)
Save-DummyArtifact -ArtifactPaths $artifactPaths -ProjectRoot $ProjectRoot -RunId $RunId -Scope run -Phase "Phase4" -ArtifactId "phase4_tasks.json" -Content $tasksArtifact

switch ($Scenario) {
    "phase5-ready" {
        Set-DummyTaskState -RunState $state -TaskId "T-01" -Status "ready" -PhaseCursor "Phase5"
        $state = Set-RunStateCursor -RunState $state -Phase "Phase5" -TaskId "T-01"
    }
    "phase6-reject" {
        Add-CompletedTaskArtifacts -ArtifactPaths $artifactPaths -ProjectRoot $ProjectRoot -RunId $RunId -TaskId "T-01" -Phase6Verdict "reject" -RollbackPhase "Phase5"
        Set-DummyTaskState -RunState $state -TaskId "T-01" -Status "in_progress" -PhaseCursor "Phase6" -LastCompletedPhase "Phase6"
        $state = Set-RunStateCursor -RunState $state -Phase "Phase6" -TaskId "T-01"
    }
    "task-group" {
        $groupId = "group-dummy-001"
        $workerIds = @("worker-T-01", "worker-T-02", "worker-T-03")
        $state["task_groups"][$groupId] = New-RunStateTaskGroup -GroupId $groupId -Status "running" -TaskIds @("T-01", "T-02", "T-03") -WorkerIds $workerIds
        foreach ($workerId in $workerIds) {
            $taskId = $workerId -replace '^worker-', ''
            $workspacePath = Join-Path (Join-Path $runRoot "workspaces") $workerId
            $artifactRoot = Get-JobArtifactsRootPath -ProjectRoot $ProjectRoot -RunId $RunId -JobId $workerId
            New-Item -ItemType Directory -Path $workspacePath -Force | Out-Null
            New-Item -ItemType Directory -Path $artifactRoot -Force | Out-Null
            $worker = New-RunStateTaskGroupWorker -WorkerId $workerId -GroupId $groupId -TaskId $taskId -Status "running" -Phase "Phase5"
            $worker["phase_sequence"] = @("Phase5", "Phase5-1", "Phase5-2", "Phase6")
            $worker["workspace_path"] = $workspacePath
            $worker["artifact_root"] = $artifactRoot
            $worker["declared_changed_files"] = @("src/$taskId.txt")
            $worker["resource_locks"] = @("file:src/$taskId.txt")
            if ($taskId -eq "T-02") {
                $worker["status"] = "succeeded"
                $worker["current_phase"] = "Phase6"
                $worker["final_phase"] = "Phase6"
                $worker["worker_result"] = [ordered]@{ worker_id = $workerId; group_id = $groupId; task_id = $taskId; status = "succeeded"; final_phase = "Phase6"; errors = @(); artifact_refs = @(); changed_files = @("src/$taskId.txt"); workspace_path = $workspacePath }
            }
            elseif ($taskId -eq "T-03") {
                $worker["status"] = "queued"
                $worker["current_phase"] = "Phase5"
            }
            $state["task_group_workers"][$workerId] = $worker
        }
        Set-DummyTaskState -RunState $state -TaskId "T-01" -Status "in_progress" -PhaseCursor "Phase5" -ActiveJobId "group:$groupId"
        $state = Set-RunStateCursor -RunState $state -Phase "Phase5" -TaskId "T-01"
    }
    "ready-ui" {
        $jobId = "job-dummy-active"
        Set-DummyTaskState -RunState $state -TaskId "T-01" -Status "running" -PhaseCursor "Phase5" -ActiveJobId $jobId
        Set-DummyTaskState -RunState $state -TaskId "T-02" -Status "ready" -PhaseCursor "Phase5" -WaitReason ""
        Set-DummyTaskState -RunState $state -TaskId "T-03" -Status "blocked" -PhaseCursor "Phase5" -WaitReason "dependency"
        $state["active_jobs"][$jobId] = [ordered]@{
            job_id = $jobId
            task_id = "T-01"
            phase = "Phase5"
            role = "implementer"
            status = "running"
            lease_owner = "dummy-run"
            slot_id = "slot-1"
            lease_token = "dummy-token"
            lease_expires_at = (Get-Date).AddMinutes(30).ToString("o")
            last_heartbeat_at = (Get-Date).ToString("o")
        }
        $state["active_job_id"] = $jobId
        $state = Set-RunStateCursor -RunState $state -Phase "Phase5" -TaskId "T-01"
    }
    "approval" {
        Add-CompletedTaskArtifacts -ArtifactPaths $artifactPaths -ProjectRoot $ProjectRoot -RunId $RunId -TaskId "T-01" -Phase6Verdict "go" -RollbackPhase ""
        Set-DummyTaskState -RunState $state -TaskId "T-01" -Status "in_progress" -PhaseCursor "Phase5-1" -LastCompletedPhase "Phase5"
        $state["pending_approval"] = [ordered]@{
            id = "approval-dummy-001"
            phase = "Phase5-1"
            role = "reviewer"
            task_id = "T-01"
            requested_at = (Get-Date).ToString("o")
            reason = "Dummy pending approval for UI and resume testing"
        }
        $state = Set-RunStateCursor -RunState $state -Phase "Phase5-1" -TaskId "T-01"
    }
}

$state["updated_at"] = (Get-Date).ToString("o")
Write-RunState -ProjectRoot $ProjectRoot -RunState $state | Out-Null

$manifest = [ordered]@{
    schema_version = 1
    generated_by = "relay-dev-dummy-run"
    generated_at = (Get-Date).ToString("o")
    scenario = $Scenario
    run_id = $RunId
    project_root = $ProjectRoot
    run_root = $runRoot
    run_state_path = Get-RunStatePath -ProjectRoot $ProjectRoot -RunId $RunId
    artifacts = @($artifactPaths.ToArray())
}
$manifestPath = Join-Path $runRoot "dummy-run-manifest.json"
Set-Content -Path $manifestPath -Value (($manifest | ConvertTo-Json -Depth 50) + "`n") -Encoding UTF8
$runStatePath = [string]$manifest["run_state_path"]
$artifactCount = @($artifactPaths.ToArray()).Count

[ordered]@{
    ok = $true
    scenario = $Scenario
    run_id = $RunId
    project_root = $ProjectRoot
    run_root = $runRoot
    run_state_path = $runStatePath
    manifest_path = $manifestPath
    artifact_count = $artifactCount
    next_commands = @(
        "pwsh -NoLogo -NoProfile -File app\cli.ps1 show -RunId $RunId",
        "Get-Content -Raw $runStatePath | ConvertFrom-Json"
    )
} | ConvertTo-Json -Depth 20
